---
- hosts: edewillians2c.mylabserver.com
  tasks:
    - name: touch a new file
      file:
        path: /tmp/testFile1
        state: touch
    - name: add line with copy
      copy:
        content: added by copy ansible module
        dest: /tmp/testFile2
    - name: add line with lineinfile
      lineinfile:
        path: /tmp/testFile3
        line: added by lineinfile module
        create: yes


...
