---
- hosts: edewillians2c.mylabserver.com
  become: yes
  tasks: 
    - name: perform a weekly yum update
      cron:
        name: "weekly yum update"
        minute: "*"
        hour: "2"
        month: "*"
        weekday: "0"
        user: root
        state: absent
        job: "yum -y update"

...
