---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: create user and add them to the apache group
      user:
        name: "{{ item }}"
        groups: apache
      loop:
        - will
        - myles
    - name: create index.html
      template:
        src: /home/cloud_user/ansible/templates/index.j2
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

- hosts: dbservers
  become: yes
  tasks:
    - name: install postgresql
      yum:
        name: postgresql-server
        state: latest
    - name: initialize db cluster
      command: /usr/bin/postgresql-setup --initdb
    - name: create users
      user:
        name: "{{ item }}"
        groups: postgres
      loop:
        - corey
        - arron
    - name: start and enable postgres
      service:
        name: postgresql
        state: started
        enabled: yes

...
