---
- hosts: edewillians2c.mylabserver.com
  become: yes
  tasks:
    - name: Add a repository
      yum_repository:
        name: repo_name
        description: Description of the repo
        baseurl: https://website.com/full/path/of/base/url
        gpgcheck: no
    - name: Remove a repository from a repo file
      yum_repository:
        name: repo_name
        file: repo_file_name (without the ".repo" extention)
        state: absent

...
