---
- hosts: edewillians2c.mylabserver.com
  become: yes
  tasks:
    - name: start and enable httpd service
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: start and enable the firewalld service
      systemd:
        name: firewalld
        state: restarted
        enabled: yes
...

