---
- hosts: all
  become: yes
  tasks:
    - name: show options for user module
      user:
        name: user_name
        shell: /bin/bash|/bin/zsh|etc
        home: /path/to/home/dir
        comment: user description
        uid: set the uid of the user
        group: set the user's primary group
        groups: list of the groups to add the user to 
        append: no|yes # yes: add the user to the groups specified in groups, no:user will only be added to the groups specified in groups, removing them fr                       # om all other groups
        state: present|absent
    - name: show options for the group module
      group:
        name: group_name
        gid: set the gid for the group
        system: no|yes
        state: present|absent
...
