---
- hosts: webservers
  become: yes
  tasks:
    - name: copy file
      copy:
        src: /home/cloud_user/index.html
        dest: /var/www/html/index.html
      when: ansible_hostname == "edewillians3c"
...
